language: c

addons:
  apt:
    packages: gcovr

branches:
  only:
    - master
    - development

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test

after_success:
- bash <(curl -s https://codecov.io/bash) -f "!*/tests/**/*" || echo "Codecov did not collect coverage reports"
